_wandb:
    value:
        cli_version: 0.23.1
        e:
            ebakr7w9h1jhaau3xi126vap530fwcz3:
                codePath: src/my_project/train.py
                codePathLocal: src/my_project/train.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1081101176832"
                        used: "29845270528"
                email: armandgatiusugalde@gmail.com
                executable: /home/arman/miniconda3/envs/mlops/bin/python
                git:
                    commit: 541c0328be7bccf8b4d18ca11450f7483c232107
                    remote: https://github.com/armandgatius/Mlops_practice_cookie.git
                host: ArmandHP
                memory:
                    total: "7967272960"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/arman/Mlops/Mlops_practice_cookie/src/my_project/train.py
                python: CPython 3.11.14
                root: /home/arman/Mlops/Mlops_practice_cookie
                startedAt: "2026-01-13T14:06:09.296701Z"
                writerId: ebakr7w9h1jhaau3xi126vap530fwcz3
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
